
module.exports = {
    PORT: '3000',
    DB_IP: 'localhost',
    DB_PORT: '27017',
    DB_NAME: 'signal-bridge',
    API_KEY_BINANCE: 'brIngStyOnThERihMBRelick',
    API_SECRET_BINACE: 'ichArLlisSohnOvNIIHratS',
    TIMEOUT_OPTION_BINANCE: 60000,
    VERBOSE_OPTION_BINANCE: true,
    RECONNECT_OPTION_BINANCE: true,
    ENABLE_RATE_LIMIT_OPTION_BINANCE: true,
    DEFAULT_TYPE_OPTION_BINANCE: 'future',
    LEVERAGE_OPTION_BINANCE: 3,
    MARGIN_MODE_OPTION_BINANCE: 'ISOLATED'
};